version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'java-postgres'
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: default_database
    volumes:
      - ./db-data/:/var/lib/postgresql/data/


volumes:
  postgres-data: